name: Flake8 Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: advanced-security/python-lint-code-scanning-action@v1
        with: 
          linter: flake8
          python-version: ${{ matrix.python-version }}
    
